Repository rsj-rishabh/urbanClapClone, pull requests merged in 2022-02, with the labels that each got.

#19 added example for gorm and json apis
  .DS_Store
  db/sqlite3
  db/ucc_services.db
  db/ucc_services.sql
  db/ucc_users.db
  db/ucc_users.sql
  server/app/app.go
  server/app/handler/common.go
  server/app/handler/employees.go
  server/app/model/model.go
  server/config/config.go
  server/go.mod
  server/go.sum
  server/main.go
  test/test.go
Labels: feature request

#20 adding user APIs
  .DS_Store
  db/ucc_users.sql
  server/.DS_Store
  server/app/.DS_Store
  server/app/app.go
  server/app/handler/employees.go
  server/app/handler/users.go
  server/app/model/model.go
  server/config/config.go
Labels: duplicate

#21 Adding Service API
  server/app/app.go
  server/app/handler/services.go
  server/app/model/model.go
  server/go.mod
Labels: bug

#27 Madhuri
  client/clientCode/src/app/app.component.html
  client/clientCode/src/app/app.module.ts
  client/clientCode/src/app/login/login.component.ts
  client/clientCode/src/app/register/register.component.ts
Labels: feature request

#33 Cache cleanup
  .DS_Store
  .gitignore
  client/clientCode/.angular/cache/13.1.4/angular-webpack/5951189e6c6f64d1bfba242b09b015ae23857062/0.pack
  client/clientCode/.angular/cache/13.1.4/angular-webpack/5951189e6c6f64d1bfba242b09b015ae23857062/1.pack
  client/clientCode/.angular/cache/13.1.4/angular-webpack/5951189e6c6f64d1bfba242b09b015ae23857062/index.pack
  client/clientCode/.angular/cache/13.1.4/angular-webpack/5951189e6c6f64d1bfba242b09b015ae23857062/index.pack.old
  client/clientCode/.angular/cache/13.1.4/babel-webpack/082a1b9aedd363855e11e3bdbb0c2bf0.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/137f4545e52265098e71a1aa97b5e43d.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/1b4b6f056747e1678e9eac79e9056595.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/2d90718e65841f882abb0f5aa42973cc.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/365c419cafc9e475eb9f5e19a0b4e023.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/3a1844efc322818bc0a0cdfec3335776.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/40bf285c0b6869236ef0af7c8b601ee0.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/619c0dbd2529a9ddac12891f6e462c35.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/64e2147f7f457def0269f850f157c77b.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/73c86b58b19a02b2c10b45f0f44e53c4.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/841f46c38a183789c034ca1f488633db.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/89740092c5846624d43cd5cfa1be2a54.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/940fa6fb9db27ba646faae795f12674e.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/967cf9e46fd05a0d3201e8c84e48221d.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/a1f52f89a323157344c5cde61861298d.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/a85d878427d236dd9c8e7c72e88065e2.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/aa175b513e6321088793619047791bcf.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/af941e091c644394fc5419ebf22c1b6d.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/b9c40c898f22a2ce33aa289fc876fe26.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/c2ae50c6ea03f07e5da61927327755d7.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/fd921b7e7ce1175a83208de325b24320.json
  client/clientCode/.angular/cache/13.1.4/babel-webpack/fe6506044bbcf685963f914366516c32.json
  server/.DS_Store
  server/app/.DS_Store
Labels: help wanted

#36 Edited welcome text
  client/clientCode/src/app/landing/landing.component.html
  server/package-lock.json
Labels: enhancement

#38 Sprint1 Report Update
  Sprint1.md
Labels: documentation

#63 fixed CORS issue and added booking DB
  client/clientCode/src/app/register/register.component.ts
  db/ucc_bookings.sql
  db/ucc_services.sql
  server/app/app.go
  server/app/handler/users.go
  server/main.go
Labels: bug, feature request, enhancement

#67 Create UccAPIs.postman_collection.json
  UccAPIs.postman_collection.json
Labels: documentation

#68 Adding booking API
  server/app/handler/bookings.go
Labels: feature request

#70 fixed service and user APIs
  server/app/handler/services.go
  server/app/handler/users.go
  server/config/config.go
  server/go.mod
Labels: bug

#71 Create go.yml
  .github/workflows/go.yml
Labels: test request

#73 book service API implementation
  UccAPIs.postman_collection.json
  server/app/handler/bookings.go
  server/app/init.go
  server/app/model/model.go
Labels: feature request
